### ISSUE TITLE
How do i login as an admin , the app doesnt respond to admin login?

### ISSUE THREAD

**Issue by PranshuKala** [TejoVarma/CAR-RENTAL-APP#36]

**Comment by TejoVarma** [comment]
first register as admin and then try logging in.

**Comment by PranshuKala** [comment]
Can you please tell instructions to run this app locally?

**Comment by TejoVarma** [comment]
first of all you download the zip file or else you can clone the repo and try. After that create a .env file in server folder and in that file write DB_URL = 'Create a mongoDb Atlas URL and paste it here', DB_NAME = 'Your DB name', DB_COLLECTION = 'name of your choice but images is preferable', PORT = 'Your wish the server runs in that port', SECRET = 'some secret name of your choice'

for client to run go to client folder and start with npm start

for server to run go to server/src  and start with npm start


and one more thing you will not get maps because it is deleted create you own key to do that
